easy_admin:
    entities:
        Product:
            class: App\Entity\Product
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'description' }
                    - { property: 'price' }
                    - { property: 'imageFile', type: 'vich_image' }